apiVersion: v1
kind: ConfigMap
metadata:
  name: webappinfo
  namespace: {{ .Values.namespace }}
data:
  bgimage: "s3://clo835bgimg/bg5.jpg"
  ournames: "Islamiyat Osuolale, Kamaal Bolton, Naveendran Wijeyasekaran, Oluwole Amusan, Superman, Thor, Ryan Reynolds, Miles Morales"
  dbuser: "dbadmin"